### PR TITLE
lep: Add Custom UV Streams

### PR DESCRIPTION
**Pull request by coderkevin**
This LEP describes a first draft for adding custom streams to libuv.

### CODE REVIEW

**Comment by coderkevin** [comment]
@saghul I'm going to start experimenting with this in my own fork at https://github.com/coderkevin/libuv/tree/custom-streams, to see how it would work.  Please let me know any feedback, questions, or concerns you've got.

@bnoordhuis and @piscisaureus Are there concerns with this type of feature?  I feel there's some inside joke I'm not getting.

**Comment by piscisaureus** [comment]
@coderkevin 

Not much of an in-joke. I've been saying over and over that we need a feature like the one you're proposing, but I never really did any work to that end. You're fully encouraged to fork & experiment!

**Comment by coderkevin** [comment]
@piscisaureus that's good news.  I'll keep going then and update progress here.  I'm pretty new here too, so I'd appreciate any input or reviews, for sure.  Thanks!

**Comment by saghul** [comment]
Rejected as discussed in (https://github.com/libuv/libuv/issues/275#issuecomment-109895708). Landed in 4b9271a.

**Pull request closed without merging**
