### PR TITLE
lep: threadpool handle

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by beevik** [comment]
+1 on the user-supplied threadpool proposal.

Setting up a threadpool might be considered a bit of an advanced thing to do in order to use libuv, so I assume the default libuv initialization will still rely on libuv-supplied threadpool(s). If so, will the Windows version unify the Windows API threadpool and libuv-internal threadpool?

**Comment by saghul** [comment]
> Setting up a threadpool might be considered a bit of an advanced thing to do in order to use libuv, so I assume the default libuv initialization will still rely on libuv-supplied threadpool(s).

Actually no. The idea is that the user creatres a threadpool handle and it just uses it when calling some function which runs in the threadpool, see the uv_getaddrinfo example. The thread management is done internally.

> If so, will the Windows version unify the Windows API threadpool and libuv-internal threadpool?

This LEP doesn't contemplate that, and right now I'm not sure it could be done because those threads are internal. FWIW I'm not even sure we do any allocations in those threads, which are only used in some special cases when emulating IOCP on pipes.

**Comment by saper** [comment]
I am not sure priorities can handle the situation where two different families of work queue clients are co-dependent in some way. (My case is described here https://github.com/sass/node-sass/issues/857#issuecomment-93594360 - collision of custom queue jobs with the filesystem API).

What would *really* help (I think that would be a TrueNodeWay) is ability to tell queue runner periodically to allow other queue items to run (kind of `process.nexttick`, maybe). Running under `node` I cannot talk to V8 from the threadpool worker thread, but it should be possible to talk to the queue runner.

Instead of waiting on a lock in https://github.com/sass/node-sass/blob/master/src/callback_bridge.h#L99 I could tell the queue manager "Please let other callbacks run in the meantime". 

Even nicer and more flexible solution (maybe out of scope of this PR) would be to implement coroutines in `libuv`. Something like a lightweight pipe between wq threads. Or even real coroutines using [libcoro](http://cvs.schmorp.de/libcoro/). So I can postpone one work item and switch to another, keeping thread context saved in the queue. `uv_work_yield()` anyone? :)

**Comment by NatalieWolfe** [comment]
Is there any movement on this proposal? I would like to see libuv's thread pooling... adjusted, and would like to create a counter-proposal that follows closer to @bnoordhuis's suggestion if this one has gone as stale as it appears.

**Comment by saghul** [comment]
@NatalieWolfe there are a number of patches/issues/proposals lingering around about the thread-pool. I have plans to open some "meta-issue" and discuss the state of affairs soon, will @ you there. This proposal and what Ben proposed are not necessarily orthogonal, it does need some updating though.

**Comment by trevnorris** [comment]
@bnoordhuis 
> For example, there is no way to express that some requests should have a higher priority than others. (Granted, libuv does not have such functionality anyway but see below.)

This sounds a lot like GCD and its dispatch queue priority (https://developer.apple.com/library/ios/documentation/Performance/Reference/GCD_libdispatch_Ref/#//apple_ref/doc/constant_group/dispatch_queue_priority_t).

**Comment by bminer** [comment]
Any update on this?

**Comment by saghul** [comment]
Sorry, no updates yet.

**Comment by saghul** [comment]
REJECTED: The libuv core team (part of it) gathered together at Node Interactive Amsterdam 2016 and decided
to withdraw this course of action and focus on a pluggable API for threaded operations. A new
LEP will be written about it.

**Comment by bminer** [comment]
@saghul - Could you provide more info when it becomes available?  Thanks!

**Comment by saghul** [comment]
Sure, I'll drop a note here.  Cheers!

**Comment by bminer** [comment]
Any updates on threads and `uv_queue_work`?  Another problem in Node is hanging threads from user code that prevent Node from terminating (threads are usually blocked by an I/O system call, i.e. `read`).

What is the consensus on the path forward?

**Comment by davisjam** [comment]
@bminer I have resumed working on a PR for a pluggable threadpool. Follow at [#1726](https://github.com/libuv/libuv/pull/1726). I'm currently in the process of remembering things after summer break.

**Pull request merged**
